export const HTTP_STATUS = Object.freeze({
	BAD_REQUEST: 400,
	UNAUTHORIZED: 401,
	FORBIDDEN: 403,
	NOT_FOUND: 404,
	CONFLICT: 409,
	UNPROCESSABLE_ENTITY: 422,
	TOO_MANY_REQUESTS: 429,
	NOT_IMPLEMENTED: 501,
	INTERNAL_SERVER_ERROR: 500,
});

export const PARTICIPATION_ERROR_CODES = Object.freeze({
	VALIDATION_ERROR: "VALIDATION_ERROR",
	AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
	GIVEAWAY_NOT_FOUND: "GIVEAWAY_NOT_FOUND",
	PRIZE_NOT_FOUND: "PRIZE_NOT_FOUND",
	PRIZE_NOT_IN_GIVEAWAY: "PRIZE_NOT_IN_GIVEAWAY",
	GIVEAWAY_NOT_ACTIVE: "GIVEAWAY_NOT_ACTIVE",
	USER_NOT_ELIGIBLE: "USER_NOT_ELIGIBLE",
	INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
	DUPLICATE_PARTICIPATION: "DUPLICATE_PARTICIPATION",
	FRAUD_REJECTED: "FRAUD_REJECTED",
	RATE_LIMITED: "RATE_LIMITED",
	PARTICIPATION_NOT_IMPLEMENTED: "PARTICIPATION_NOT_IMPLEMENTED",
});
